spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      #format_sql: true