spring:
  main:
    allow-circular-references: true
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"
    fallbackToSystemLocale: false
application:
  file: "questions.csv"
  threshold: 2
  locale: ru_RU