spring:
  datasource:
    url: jdbc:h2:mem:librarydb
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    rest:
      base-path: /datarest
  jmx:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    circuitbreakers:
      enabled: true
logging:
  file:
    name: logs/library.log
resilience4j:
  circuitbreaker:
    instances:
      database:
        failure-rate-threshold: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
    configs:
      default:
        registerHealthIndicator: true