spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 0
      database: libraryDB

  datasource:
    url: jdbc:h2:mem:librarydb

  h2:
    console:
      enabled: true
      path: /h2-console
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

logging:
  level:
    root: error

app:
  chunk-size: 2